// Three character proposals for the programmer. All share one rig; they differ in proportions,
// silhouette details, colours and face language.
export const DESIGNS = {
  A: {
    id: 'A',
    title: '方案 A · 软卫衣',
    en: 'Soft Hoodie',
    blurb: ['宽松的雾蓝卫衣把肩、肘都包进一块柔软的形状里，', '蓬松的深棕头发是一整团，会随熬夜越来越乱，', '头顶一根呆毛负责"跟随动作"。竖椭圆的眼睛呼应小方块。'],
    notes: ['卫衣 = 一整块会挤压拉伸的形体，没有可见关节', '头发 / 呆毛 / 帽绳 三处跟随动作', '竖椭圆眼 + 短粗眉，表情靠眼皮和眉毛', '四指简化手，手指是一整块轮廓'],
    hoodie: '#7f9dba', hoodieShade: '#6885a4', hoodieDeep: '#56718f', hoodieLight: '#a3bdd4', strings: '#f4ecdc',
    pants: '#4d4b57', pantsShade: '#3e3c47', socks: '#efe6d6', socksShade: '#d3c8b4',
    skin: '#f7dcc5', skinShade: '#e9bf9f', blush: '#f2a08f', hair: '#3a2a23', hairHi: '#5e473b', lip: '#b8624f',
    headScale: 1.1, hairStyle: 'fluffy', glasses: false, hat: null, eyes: 'oval', face: 'oval', hands: 'four',
    shW: 16.5, chestW: 18.2, hemW: 17.4, torsoH: 50, upper: 25, fore: 24, sleeve: 5.4,
  },
  B: {
    id: 'B',
    title: '方案 B · 圆眼镜',
    en: 'Round Glasses',
    blurb: ['黑色中分短发，圆框眼镜是他的标志。', '镜片能反射屏幕：测试失败时映出红光，全绿时映出绿光，', '不用对白就能讲清屏幕上发生了什么。橄榄绿卫衣。'],
    notes: ['眼镜反光 = 叙事工具（红 / 绿 / 晨光）', '中分刘海是两片整块，甩头时跟随动作明显', '豆豆眼 + 眉毛露在刘海下，表情清楚', '比例稍修长，更像大学生 / 年轻工程师'],
    hoodie: '#7e9a78', hoodieShade: '#688462', hoodieDeep: '#556e50', hoodieLight: '#a2b99b', strings: '#f4ecdc',
    pants: '#474552', pantsShade: '#393744', socks: '#e9e2d6', socksShade: '#cfc5b3',
    skin: '#f6dbc3', skinShade: '#e5bb9b', blush: '#f0a08e', hair: '#23201f', hairHi: '#48413c', lip: '#b8624f',
    headScale: 1.06, hairStyle: 'fringe', glasses: true, hat: null, eyes: 'dot', face: 'oval', hands: 'four',
    shW: 16, chestW: 17.4, hemW: 16.8, torsoH: 51.5, upper: 25.5, fore: 24.5, sleeve: 5.1,
  },
  C: {
    id: 'C',
    title: '方案 C · 毛线帽',
    en: 'Beanie',
    blurb: ['最"方块"的一版：圆角方形的脸、竖长方形的眼睛，', '和小方块像是一家人。芥末黄毛线帽 + 帽顶小绒球，', '绒球和帽檐下的碎发负责跟随动作。薰衣草紫卫衣。'],
    notes: ['和小方块同一套造型语言（圆角方 + 竖长眼）', '无指手套式的手：最稳、最好动画', '绒球是最明显的跟随 / 回弹部件', '头身比最卡通，表情幅度最大'],
    hoodie: '#a497c4', hoodieShade: '#8b7eae', hoodieDeep: '#766a98', hoodieLight: '#c1b7db', strings: '#f4ecdc',
    pants: '#4b4a55', pantsShade: '#3d3c46', socks: '#efe6d6', socksShade: '#d3c8b4',
    skin: '#f7dcc5', skinShade: '#e9bf9f', blush: '#f2a08f', hair: '#4a3226', hairHi: '#6b5041', lip: '#b8624f',
    beanie: '#e9b949', beanieShade: '#cf9c2f', beanieLight: '#f3d27c',
    headScale: 1.18, hairStyle: 'beanie', glasses: false, hat: 'beanie', eyes: 'rect', face: 'squircle', hands: 'mitten',
    shW: 16.5, chestW: 18.4, hemW: 17.8, torsoH: 48, upper: 24, fore: 23, sleeve: 5.6,
  },
};
